name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: install devbox
        uses: jetpack-io/devbox-install-action@v0.7.0

      - name: build project
        id: build
        run: |
          devbox run make
          cp *.hex fluffy58.hex

      - name: release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: fluffy58.hex

      - uses: actions/upload-artifact@v3
        with:
          name: fluffy58 firmware for lily58
          path: fluffy58.hex
